### ISSUE TITLE
test_reduce_h sproadically failing in slow dispatch mode

### ISSUE THREAD

**Issue by TT-billteng** [tenstorrent/tt-metal#10181]
https://github.com/tenstorrent/tt-metal/actions/runs/9897229545/job/27341497229
https://github.com/tenstorrent/tt-metal/actions/runs/9868680454/job/27251730305

**Comment by tt-rkim** [comment]
This is disabled now on main by @TT-BrianLiu 
Should we keep this open? We don't really use this old style C++ tests anymore, but the fact that it fails is concerning

**Comment by TT-billteng** [comment]
I'm concerned that this is the ONLY test that fails

**Comment by pgkeller** [comment]
I think this should be fixed, there was a  race in llk init related to this.  assigned Samarth to try it out

**Comment by TT-billteng** [comment]
@sagarwalTT ?

**Comment by sagarwalTT** [comment]
@prajaramanTT @TT-billteng This is still an open issue, I'll run this a couple of times to see if it's still failing in SD. If it doesn't fail, I'll enable the test and close this.

**Comment by sagarwalTT** [comment]
This is still failing: https://github.com/tenstorrent/tt-metal/actions/runs/12658798175/job/35277845763#step:5:5641

**Comment by tt-rkim** [comment]
@pgkeller Can the team take another look at this?

**Comment by pgkeller** [comment]
yes, this will be next up for Samarth after his current task

**Comment by pgkeller** [comment]
maybe related to #14510 ?

**Comment by tt-rkim** [comment]
This seems to be on GS, the other one too

Not sure how much we care anymore... unless you guys think it could possibly be exposing a bug within the dispatch system.

**Comment by pgkeller** [comment]
13452 was WH which I can no longer reproduce.  We don't need to worry about GS now.  Closing
