### ISSUE TITLE
Moreh CCL Test Hanging on T3000MultiCQMeshDeviceFixture.AsyncExecutionWorksCQ0CQ1

### ISSUE THREAD

**Issue by cfjchu** [tenstorrent/tt-metal#20375]

**Comment by sminakov-tt** [comment]
I investigated the issue, and it is related to Moreh's extension of the test to enqueue extra dummy operations. There is even a [comment](https://github.com/tenstorrent/tt-metal/pull/19895#issuecomment-2767739141) about the hang, but it is claimed as resolved in this [comment](https://github.com/tenstorrent/tt-metal/pull/19895#issuecomment-2767768542), which isn't actually the case. I did observe a strange behavior, where if I run a single test it passes, but if I run a binary with the two tests - the second one freezes.

I did further investigation of the freeze, and the freeze is fixed with this [commit](https://github.com/tenstorrent/tt-metal/pull/18067/commits/298ef24084376a0c730a6c4589dbbc9eeac44370) to the integration branch.

However, there is a real issue with our Fabric or CCLs. There is a reproducible freeze if a an op is enqueued while CCL is being executed on another CQ. I added a TODO: `investigate why other OPs can't be scheduled on a different command queue until CCL is finished` in the tests. I believe the issue is currently present in main, and I will file a separate ticket with CCL team right after the integration branch is merged, so the team would have a test to reproduce.
cc @ilkoo-lee

**Comment by ilkoo-lee** [comment]
@sminakov-tt 
It seems that my [changes](https://github.com/tenstorrent/tt-metal/pull/19895/commits/2b89b7ef0b344b59faa893e3ef4a6dd0e8620e48) were not included in that [commit](https://github.com/tenstorrent/tt-metal/pull/18067/commits/298ef24084376a0c730a6c4589dbbc9eeac44370) (perhaps the conflict was not resolved correctly). Using boost::asio::strand is the correct approach."
