### ISSUE TITLE
[6U Llama3-70B] Hangs on Stress test - g05glx6u02/g05glx6u04

### ISSUE THREAD

**Issue by djordje-tt** [tenstorrent/tt-metal#20641]
# Description

During stress testing on g05glx6u02 and g05glx6u04, the system hangs in the 3rd pytest run between iterations 1700–1800 and 5200+ respectively. Due to suppressed logging (extensive printing mitigation), progress is only shown every 100 iterations, making precise hang detection difficult. 
### What is stress test: 
A bash script (`run_stress_test_in_a_loop_6u.sh`) that runs `decode-demo` 5 times in a row, generating **20.000** tokens per run.
### Why testing it on 6U
Group of 4U galaxies were hanging while another group was passing consistently without noticeable difference. Further Investigation paused on 4U; now verifying if the same issue occurs on 6U.
### Current 4U CI
This test is not in CI due to resource constraints and also some 4U CI machines were observing hangs while running this test. A mini-stress-test (2K tokens, single run) was added recently and passes reliably.

# Steps to reproduce

- `Branch`: https://github.com/tenstorrent/tt-metal/tree/divanovic/6u_galaxy_stress_testing
- Ensure `tt-metal` is compiled in Release mode. 
- Run:
```
chmod +x run_stress_test_in_a_loop_6u.sh
./run_stress_test_in_a_loop_6u.sh g05glx6u02
```
### Known Issue
In case a run hangs reset will probably not work so you won't be able to run for full 5 iterations but only up to the one where it hangs. Once reset sequence works properly script will be able to recover from hang.

**Comment by tt-rkim** [comment]
Who's going to take a look at this? @uaydonat

**Comment by uaydonat** [comment]
@djordje-tt will investigate based on feedback we received from Milos yesterday

**Comment by djordje-tt** [comment]
Hi @ttmtrajkovic, Utku mentioned that we will have an option to delay matmuls. I believe it's the stagger feature, right? Is it already available on 6U galaxies to try it out with these stress tests or no?

**Comment by uaydonat** [comment]
@djordje-tt I spoke to Milos. The plan is:

1. run the stress test even longer, maybe 1 day on each of the machines to confirm the good machines and bad machines.
2. take matmul+prefetcher test, run this many iterations (~1 day) on bad machines and see if we can reproduce.
3. If not, let's figure out which op is hanging during the full llama with help from runtime team and create a unit test for it.

Once we have a unit test, we can share it with the syseng team and look at it together.

**Comment by tt-rkim** [comment]
We may have found a source of issues for `g05glx6u01`: https://github.com/tenstorrent/cloud/issues/4451

**Comment by tcolacoTT** [comment]
Are there still Llama stress test hangs being observed on 6U Galaxy? Per messages last week (I believe related to https://github.com/tenstorrent/tt-metal/pull/21324 ) this is resolved?

Looking for confirmation to see if there are still issues against these two machines (g05glx6u02/g05glx6u04)

**Comment by tt-rkim** [comment]
@uaydonat 's team has tested

- `g05glx6u01`
- `g05glx6u04`
- `g11glx6u02`
- `g11glx6u03`

for Llama hang stress testing, and all passed.

`g05glx6u02` has not been tested.

**Comment by kpaigwar** [comment]
@tt-rkim yes the main is stable on this four machines

**Comment by tt-rkim** [comment]
This is looking good so far, but still not enough to be closed in my opinion.

Once it's closed, we can consider it a done deal and add to upstream tests and expand 6U coverage.

By the way, are there smaller unit tests we can use to stress test parts of llama? That will be extremely helpful. Maybe parts we know tend to hang or fail often.

**Comment by ejouretTT** [comment]
@tt-rkim sorry what are we waiting on to close this issue? more devices tested? a fix to be merged/ validated?

**Comment by tt-rkim** [comment]
I believe @kpaigwar wanted to do some more stress testing. Can we confirm? @kpaigwar

**Comment by ttmtrajkovic** [comment]
@tt-rkim, @djordje-tt, @ejouretTT, @uaydonat 

I would recommend to keep this opened until all POR systems are screened and a baseline is established - same hash.
@uaydonat, this is super important for the systems health. Could someone on your team prioritize this?

Thanks.

Milos

**Comment by tt-rkim** [comment]
Of currently usable PORs, only `g05glx6u03` is left to be tested with this Llama stress test. All other PORs are out of service and are being looked at by vendor or infra teams.

We have given Ammar, Djordje, and Kartik suggestions on how to schedule such tests at night for their own convenience and sanity + not to disturb others.

**Comment by tt-rkim** [comment]
Still waiting on Models team to do their testing. We've given them suggestions as noted above.

**Comment by djordje-tt** [comment]
@kpaigwar, did you manage to get last working 6U non-CI tested? `g11glx6u02`. For CI machine I will schedule Stress test today since we have a workflow for it! 
All other machines are either down or under maintenance.

**Comment by uaydonat** [comment]
Closing since we are not seeing random hangs anymore
