### ISSUE TITLE
Distributed norms run OOM in L1 for large hidden dims

### ISSUE THREAD

**Issue by cglagovichTT** [tenstorrent/tt-metal#29728]
Distributed layernorm and rmsnorm fail due to L1 OOM when hidden dim is sufficiently large. This is because the kernels (both pre_all_gather and post_all_gather steps) buffer the entire hidden dim rather than streaming in blocks. 

## Repro
branch [cglagovich/29728](https://github.com/tenstorrent/tt-metal/tree/cglagovich/29728)

```
pytest tests/test_distributed_norm_OOM.py
```

### Expected output
```
PASSED tests/test_distributed_norm_OOM.py::test_distributed_norm_comparison[wormhole_b0-device_params0-mesh_device0-rms_norm-1e-06-8192-1024-1]
FAILED tests/test_distributed_norm_OOM.py::test_distributed_norm_comparison[wormhole_b0-device_params0-mesh_device0-layer_norm-1e-06-8192-1024-1] - RuntimeError: TT_THROW @ /home/cglagovich/tt-metal/tt_metal/impl/program/program.cpp:906: tt::exception
FAILED tests/test_distributed_norm_OOM.py::test_distributed_norm_comparison[wormhole_b0-device_params0-mesh_device0-layer_norm-1e-06-16384-1024-1] - RuntimeError: TT_THROW @ /home/cglagovich/tt-metal/tt_metal/impl/program/program.cpp:906: tt::exception
FAILED tests/test_distributed_norm_OOM.py::test_distributed_norm_comparison[wormhole_b0-device_params0-mesh_device0-rms_norm-1e-06-16384-1024-1] - RuntimeError: TT_THROW @ /home/cglagovich/tt-metal/tt_metal/impl/program/program.cpp:906: tt::exception
```

**Comment by ejouretTT** [comment]
@vsureshTT any update on when this may get addressed?

**Comment by vsureshTT** [comment]
Hi all, 

This issue should be fixed with this PR. Will update again when this is merged

https://github.com/tenstorrent/tt-metal/issues/29723

**Comment by ejouretTT** [comment]
PR - https://github.com/tenstorrent/tt-metal/pull/31702

**Comment by vsureshTT** [comment]
Closing Pr is merged

https://github.com/tenstorrent/tt-metal/pull/31702

**Comment by cglagovichTT** [comment]
Found that OOM issues are still present in `ttnn.layer_norm_post_all_gather`.

Repro:
On a BH QB, the following parameters in `tests/ttnn/unit_tests/operations/fused/test_distributed_layernorm_exhaustive.py`
```
@pytest.mark.parametrize("batch_size", [1])
@pytest.mark.parametrize("seq_len", [16384])
@pytest.mark.parametrize("hidden_dim", [5120*2])
@pytest.mark.parametrize("eps", [1e-5])
@pytest.mark.parametrize(
    "mean, var, outlier_pct, outlier_var",
    [
        (0, 1, 0, 0),
    ],
    ids=[
        "standard_normal",
    ],
)
@pytest.mark.parametrize(
    "norm_type, use_legacy, use_welford",
    [
        ("layer_norm", False, True),  # LayerNorm with Welford
    ],
    ids=["layer_norm_welford"],
)
# @pytest.mark.parametrize("mesh_device", [(1, 8)], indirect=True)
@pytest.mark.parametrize("mesh_device", [(1, 4)], indirect=True)
@pytest.mark.parametrize(
    "device_params",
    [
        {"fabric_config": ttnn.FabricConfig.FABRIC_1D},
    ],
    indirect=True,
)
def test_distributed_norm_allclose
# Rest unchanged
```

Expected output:
```
info:
Statically allocated circular buffers on core range [(x=0,y=0) - (x=12,y=9)] grow to 1787584 B which is beyond max L1 size of 1572864 B
```

**Comment by ejouretTT** [comment]
@vsureshTT any ETA on when this will get resolved? thanks!

**Comment by vsureshTT** [comment]
> [@vsureshTT](https://github.com/vsureshTT) any ETA on when this will get resolved? thanks!
Hey @ejouretTT,

No ETA at the moment, the corner case was taken care of by this PR by @cglagovichTT https://github.com/tenstorrent/tt-metal/pull/35657#issuecomment-3740822388 so there is nothing blocked currently

**Comment by cglagovichTT** [comment]
Correct - once https://github.com/tenstorrent/tt-metal/pull/35657 merges, this issue is resolved

**Comment by ejouretTT** [comment]
PR merged. Closing issue.
