### ISSUE TITLE
[Bug Report] CI Failure in Resnet on GS - shape invalid

### ISSUE THREAD

**Issue by jliangTT** [tenstorrent/tt-metal#7599]
**Describe the bug**

https://github.com/tenstorrent/tt-metal/actions/runs/8728814046/job/23949644058
raw log: [here](https://productionresultssa14.blob.core.windows.net/actions-results/e109d751-1a0e-4ce9-bf97-d2160e08974e/workflow-job-run-d18ab9d5-9639-5b19-5b18-74719e08498f/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-04-18T17%3A39%3A29Z&sig=7n2zV7Xp4eMdW27SuT%2Bd%2BTA8jRu1NhpwGg8pKYFq70Y%3D&sp=r&spr=https&sr=b&st=2024-04-18T17%3A29%3A24Z&sv=2021-12-02)

`2024-04-17T21:44:22.1301241Z FAILED tests/ttnn/integration_tests/resnet/test_performance.py::test_perf_device_bare_metal[batch_size=20-test=batch_size=20-act_dtype=DataType.BFLOAT8_B-weight_dtype=DataType.BFLOAT8_B-math_fidelity=MathFidelity.LoFi-expected_perf=7363] - subprocess.CalledProcessError: Command '['python -m tracy -p -r -o /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/generated/profiler/reports/ResNet50 -t 5000 -m pytest tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet50.py::test_resnet_50[batch_size=20-act_dtype=DataType.BFLOAT8_B-weight_dtype=DataType.BFLOAT8_B-math_fidelity=MathFidelity.LoFi]']' returned non-zero exit status 1.
2024-04-17T21:44:22.1302358Z FAILED tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet.py::test_basic_block_with_downsample - RuntimeError: ttnn.to_torch: Tensor must be of type ttnn.Tensor, but got <class 'NoneType'>
2024-04-17T21:44:22.1303401Z FAILED tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet.py::test_resnet_conv7s2 - RuntimeError: ttnn.to_torch: Tensor must be of type ttnn.Tensor, but got <class 'NoneType'>
2024-04-17T21:44:22.1304319Z FAILED tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet.py::test_resnet - RuntimeError: shape '[1, 1, 1600, 256]' is invalid for input of size 401408
2024-04-17T21:44:22.1306086Z FAILED tests/ttnn/integration_tests/resnet/test_ttnn_functional_resnet50.py::test_resnet_50[batch_size=8-act_dtype=DataType.BFLOAT8_B-weight_dtype=DataType.BFLOAT8_B-math_fidelity=MathFidelity.LoFi] - RuntimeError: TT_ASSERT @ tt_eager/tensor/tensor_impl.cpp:143: num_shards <= num_cores`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by nsmithtt** [comment]
Fixed w/ [b005e21](https://github.com/tenstorrent/tt-metal/commit/b005e212b95846856d70e133cacbbe38986c7743)

**Comment by nsmithtt** [comment]
Reopening, [b005e21](https://github.com/tenstorrent/tt-metal/commit/b005e212b95846856d70e133cacbbe38986c7743) is reverted.

**Comment by jliangTT** [comment]
Closing. re-opening if there are still pending issue

**Comment by mywoodstock** [comment]
reopening since batch=8 issue noted above is not yet resolved.

**Comment by jliangTT** [comment]
understood.. okay to keep it as p2 then, extending Nick message earlier.

**Comment by mywoodstock** [comment]
@nsmithtt I think we should increase the priority of this issue -- b=8 is the only case which can work with bfloat16 (higher batch only works with bfloat8_b), and we don't have any model test running for this.

**Comment by nsmithtt** [comment]
Made it a P1, I can take a look at this next.

**Comment by tt-rkim** [comment]
Thank you @nsmithtt ! 

The entire test is now essentially disabled after switching to row major sharded for the tensors: https://github.com/tenstorrent/tt-metal/issues/8296

**Comment by nsmithtt** [comment]
Closing, test reenabled
